APP_NAME = "SIG-PNP"

# url d'accès à l'application
# Remplacer par l'url de votre instance sans '/' à la fin
APP_URL = "http://carto.parc-pyrenees.fr"

# Chaine de connexion à la base de données de l'application
SQLALCHEMY_DATABASE_URI = "postgresql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB_NAME>"

# Chaine de connexion à la base de données hebergeant les données SIG
SQLALCHEMY_SIG_DATABASE_URI "postgresql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB_NAME>"

# Active (=true) ou pas (=false) le système de suivi de modification de SQLAlchemy
# Note : l'API event de SQLAchemy n'étant pas utilisée, la désactivation économise des ressources.
# Note : Patch pour suivre la supression des médias et pouvoir supprimer un fichier sur un DELETE de media
SQLALCHEMY_TRACK_MODIFICATIONS = false

# URL vers l'instance Geonature
# Remplacer par l'url de votre instance GeoNature sans '/' à la fin
GEONATURE_URL = "https://geonature.pyrenees-parcnational.fr" 

# Identifiant de l'application dans userhub
# l'application doit préalablement être déclaré dans usershub
ID_APPLICATION = 

# Logo de la structure affiché dans l'entête de l'interface
LOGO_STRUCTURE = "logo_structure.png"



# Activer le mode développement
DEBUG = true # true | false
ENV = "development" # "production" | "development"


# Configuration de la carte
CENTER = [<LAT>, <LONG>]
ZOOM_LEVEL = 10

# Fond de carte
[[BASEMAPS]]
    name = "IGN-Orthophotos"
    url = "https://wxs.ign.fr/decouverte/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities"
    layer = "ORTHOIMAGERY.ORTHOPHOTOS"
    attributions = "©IGN"
    isDefault = 0
    format = "image/jpeg"
[[BASEMAPS]]
    name = "IGN-Plan"
    url = "https://wxs.ign.fr/decouverte/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities"
    layer = "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2"
    attributions = "©IGN"
    isDefault = 1
    format = "image/png"
